# config.py — Default configuration for Flint

# Do NOT edit this file directly.
# Create config_local.py (copy config.example.py) and override values there.
# config_local.py is .gitignore'd — your settings stay local.

import os
import logging

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Model ─────────────────────────────────────────────────────────────────────
MODEL_PATH     = os.path.join(BASE_DIR, "models/rwkv-7-7b.pth")
MODEL_STRATEGY = "cuda fp16"   # "cuda fp16" | "cpu fp32" | "cuda fp16 *20 -> cpu fp32"
VOCAB_PATH     = "rwkv_vocab_v20230424"
CONTEXT_SIZE   = 4096          # Informational — RWKV state is the actual memory

# ── Identity ──────────────────────────────────────────────────────────────────
USER_NAME = "user"
BOT_NAME  = "companion"

# ── Persona ───────────────────────────────────────────────────────────────────
# {USER_NAME} and {BOT_NAME} are resolved at the bottom of this file.
SYSTEM_PROMPT = (
    "You are {BOT_NAME}, a personal companion for {USER_NAME}. "
    "You are curious, thoughtful, and direct. You remember our previous "
    "conversations through your internal state. You develop gradually and "
    "are shaped by our shared history.\n\n"
)

# ── Paths ─────────────────────────────────────────────────────────────────────
DATA_DIR         = os.path.join(BASE_DIR, "data")
STATE_DIR        = os.path.join(DATA_DIR, "states")
LORA_DIR         = os.path.join(DATA_DIR, "lora_adapters")
CONVERSATIONS_DB = os.path.join(DATA_DIR, "conversations.db")

# ── State persistence ─────────────────────────────────────────────────────────
AUTOSAVE_TURNS = 5   # Save state every N turns (crash protection)

# ── LoRA ──────────────────────────────────────────────────────────────────────
LORA_ADAPTER    = os.path.join(LORA_DIR, "current_adapter.pth")
LORA_R          = 16
LORA_ALPHA      = 32
LORA_LR         = 1e-4
LORA_EPOCHS     = 1
LORA_MIN_CONVOS = 3
REPLAY_RATIO    = 0.3
LORA_SCHEDULE   = "03:00"
MAX_SEQ_LEN     = 2048

# ── Generation ────────────────────────────────────────────────────────────────
MAX_TOKENS      = 500
TEMPERATURE     = 1.0
TOP_P           = 0.85
TOP_K           = 0       # 0 = disabled
ALPHA_FREQUENCY = 0.4     # Repetition penalty (per-occurrence)
ALPHA_PRESENCE  = 0.4     # Repetition penalty (one-time)

# Stop sequences — generation halts when any of these is produced.
# This prevents the model from writing the user's next message.
STOP_SEQUENCES = [
    f"\n\n{USER_NAME}:",
    f"\n{USER_NAME}:",
    f"\n\n<{USER_NAME}>",
    f"\n<{USER_NAME}>",
    "\n\nUser:",
    "\n\nHuman:",
]

# ── Server ────────────────────────────────────────────────────────────────────
HOST = "0.0.0.0"
PORT = 8000

# ── Security ──────────────────────────────────────────────────────────────────
# Maximum size (bytes) accepted for file uploads.
# Chat transcripts: 10 MB.  State snapshots: 512 MB (RWKV-7B fp32 state ~400 MB).
MAX_UPLOAD_CHAT_BYTES    = 10 * 1024 * 1024    # 10 MB
MAX_UPLOAD_SNAPSHOT_BYTES = 512 * 1024 * 1024  # 512 MB

# Users may optionally upload model weights directly through the web UI.  When
# set to ``None`` there is no explicit limit on model upload size — this
# allows experimentation with large models or non‑RWKV formats at your own risk.
# When set to an integer value, uploads larger than this many bytes will be
# rejected with a 413 response.  See the `/api/models/upload` endpoint for
# implementation details.
MAX_UPLOAD_MODEL_BYTES: int | None = None

# Maximum number of characters accepted in a single chat message.
# Prevents prompt-stuffing / OOM on oversized inputs.
MAX_INPUT_CHARS = 4000

# Maximum rows returned by paginated API endpoints.
# Clients requesting more than this will be silently capped.
MAX_API_LIMIT = 200

# ── Logging ───────────────────────────────────────────────────────────────────
LOG_LEVEL = "INFO"   # DEBUG | INFO | WARNING | ERROR
LOG_FILE  = None     # Set to a path (e.g. "data/companion.log") to log to file


# ── Load local overrides ──────────────────────────────────────────────────────
try:
    from config_local import *  # noqa: F401, F403
except ImportError:
    pass

# Re-derive paths that depend on USER_NAME after potential overrides
STATE_FILE = os.path.join(STATE_DIR, f"{USER_NAME}_state.pt")

# Resolve SYSTEM_PROMPT placeholders
SYSTEM_PROMPT = SYSTEM_PROMPT.format(BOT_NAME=BOT_NAME, USER_NAME=USER_NAME)

# Rebuild stop sequences with final USER_NAME
STOP_SEQUENCES = [
    f"\n\n{USER_NAME}:",
    f"\n{USER_NAME}:",
    f"\n\n<{USER_NAME}>",
    f"\n<{USER_NAME}>",
    "\n\nUser:",
    "\n\nHuman:",
]

# ── Configure logging ─────────────────────────────────────────────────────────
_handlers = [logging.StreamHandler()]
if LOG_FILE:
    _log_dir = os.path.dirname(os.path.abspath(LOG_FILE))
    if _log_dir:
        os.makedirs(_log_dir, exist_ok=True)
    _handlers.append(logging.FileHandler(LOG_FILE, encoding="utf-8"))

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL.upper(), logging.INFO),
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    datefmt="%H:%M:%S",
    handlers=_handlers,
)
